train:
  _target_: src.datasets.LJSpeechDataset
  part: "train"
  data_dir: "/content/drive/MyDrive/ljspeech_dataset"
test:
  _target_: src.datasets.LJSpeechDataset
  part: "test"
  data_dir: "/content/drive/MyDrive/ljspeech_dataset"