train:
  _target_: src.datasets.LJSpeechDataset
  part: "train"
  data_dir: "/kaggle/input/ljspeech_dataset"
test:
  _target_: src.datasets.LJSpeechDataset
  part: "test"
  data_dir: "/kaggle/input/ljspeech_dataset"