device: "auto"
train: # metrics that are calculated during training
  - _target_: src.metrics.Mel_L1
    device: ${metrics.device}
    name: "TRAIN_mel_l1"
inference: # metrics that are calculated during inference (eval)
  - _target_: src.metrics.Mel_L1
    device: ${metrics.device}
    name: "TEST_mel_l1"
