generator:  
  _target_: src.model.Generator
  input_channels: 80
  base_channels: 256
  kernel_sizes: [16, 16, 8]
  res_kernels: [3, 5, 7]
  res_dilations: [[1, 2], [2, 6], [3, 12]]
msd:
  _target_: src.model.MultiScaleDiscriminator
mpd:
  _target_: src.model.MultiPeriodDiscriminator
