generator:  
  _target_: src.model.Generator
  inp_ch: 80
  out_ch: 256
  kernel_sizes: [16, 16, 8]
  res_k: [3, 5, 7]
  res_dil: [[1, 2], [2, 6], [3, 12]]
msd:
  _target_: src.model.MultiScaleDiscriminator
mpd:
  _target_: src.model.MultiPeriodDiscriminator